### ISSUE TITLE
Traverse directories to find Chukfile

### ISSUE THREAD

**Issue by StephanHoyer** [StephanHoyer/chuk#5]
It would be nice if chuk searches for Chukfile in parents dirs

**Comment by behrendtio** [comment]
Well... Pro: One can place it's Chukfiles where ever he wants. Contra: A fixed structure makes things clearer on new projects.

How about this: `chuk`  searches in parent dirs upwards until he find's a `.git` folder, which usually means it's the root folder. No need to search in the parent of the root, since this will usually contain shitloads of other projects.

**Comment by StephanHoyer** [comment]
Sounds reasonable... let's do it... but also scan for .hg dirs.

**Comment by StephanHoyer** [comment]
https://trello.com/c/pc1n6itB

Let's use trello for all issues from now on
